import { Suspense } from "react";
import Navbar from "./components/navbar";
import Loading from "./loading";
import UserProvider from "./provider/user-provider";

export const metadata = {
  title: "BaaS POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <UserProvider>
            <Navbar></Navbar>
            {children}
          </UserProvider>
        </Suspense>
      </body>
    </html>
  );
}
