import Navbar from "./components/navbar";
import UserProvider from "./provider/user-provider";

export const metadata = {
  title: "BaaS POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <Navbar></Navbar>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
