import { Suspense } from "react";
import Navbar from "./components/navbar";
import Loading from "./loading";

export const metadata = {
  title: "BaaS POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<Loading />}>
          <Navbar></Navbar>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
